feat(reporter): log coverage threshold as a warning [#432]
karma-runner/karma-coverage pull request #433
Opened 2021-02-18 13:15 UTC by mkhodan

2021-02-18 13:18 UTC, mkhodan commented
@googlebot I signed it!

2021-02-18 13:24 UTC, mkhodan commented
will close #433

2021-05-12 08:10 UTC, anthony-redFox requested changes

2021-05-12 08:10 UTC, anthony-redFox commented on test/reporter.spec.js
> +    it.only('should log warnings on low coverage and not fail the build', async () => {
need to remove only

2021-08-05 17:49 UTC, djgrove commented
Howdy. Is this still on the radar to be added to `karma-coverage`? This is a feature I would be really excited to see as well.

2021-08-06 15:24 UTC, closed without merging

2021-09-23 14:45 UTC, djgrove commented
@mkhodan I think @anthony-redFox was waiting on you to address the above comment but there was otherwise no issue with PR. Have you removed the `only` from the above test?

2021-09-23 15:33 UTC, mkhodan commented
@djgrove this is already merged, please check #446