Correct url for Karma website
karma-runner/karma-coverage pull request #441
Opened 2021-06-08 08:57 UTC by MortenGregersen

2021-06-08 09:25 UTC, anthony-redFox commented on README.md
> +[homepage]: http://karma-runner.github.io
Will be better use https

2021-07-21 18:38 UTC, MortenGregersen commented on README.md
> +[homepage]: http://karma-runner.github.io
```suggestion
[homepage]: https://karma-runner.github.io
```

2021-08-04 16:23 UTC, anthony-redFox requested changes
please check your commits on https://www.conventionalcommits.org/en/v1.0.0/

2021-08-06 15:20 UTC, closed without merging

2021-08-06 19:43 UTC, MortenGregersen commented
> please check your commits on https://www.conventionalcommits.org/en/v1.0.0/

Better now?

2021-08-06 19:44 UTC, MortenGregersen commented
I can't reopen the pull request.